### ISSUE TITLE
CSS file still has Apache License

### ISSUE THREAD

**Issue by DeLongShot** [BlackrockDigital/startbootstrap-landing-page#10]
First, thank you for maintaining these templates and keeping them free and open-source. My issue is a small one that is about confusion with the licensing.

tl;dr The custom CSS file still has the Apache License at the top.

It looks like the MIT License conversion was started, but hasn't made it into a new release. I was a bit confused when I downloaded the latest release from the template site and it still had the Apache License, but the site says they've all been switched to MIT. I see now that I can download the source direct from GH which has the new MIT License, but as a heads up, the custom CSS file still has the Apache License information at the top.

EDIT: there's no custom JS file. Just the CSS file.

**Comment by davidtmiller** [comment]
I'll take a look, thanks!
