### ISSUE TITLE
Template works locally but not on web Server

### ISSUE THREAD

**Issue by wonderkey2** [BlackrockDigital/startbootstrap-landing-page#15]
Dear Creative,

I enjoy your template very much and customized it for my companies landing page. It works perfectly on my (Linux) Computer in a simple sub-directory. If I click on any of the pages, Firefox opens and shows everything in place (and working).
When I uploaded the entire content of my sub directory, I received a page where everything works but css and images. Means: All links and texts are shown, but no styling, no imgages.
I considered my customisation could be the reason and uploaded the plain template with the same result. Do you have any hint for me, what could be wrong after uploading to a webspace?

Many thanks in advance!

Sincerely Yours

-Marcus

**Comment by yong0011** [comment]
@wonderkey2  I think that problem about File Permission on your Server 
and you can see that document by this link [Changing File Permissions Docs](https://codex.wordpress.org/Changing_File_Permissions)
