### ISSUE TITLE
Can't change the background image in .CSS file 

### ISSUE THREAD

**Issue by bazilk** [BlackrockDigital/startbootstrap-landing-page#40]
Hi completely new to coding. been following a tutorial on using HTML and CSS temples. pretty much following it word for word even using the template they use in the tutorial (its a lighthouse labs tutorial btw) basically I can't seem to change the background image to another one in the CSS  file. been driving me crazy as I 'm putting the info into the letter in the URL . Is there something I'm missing regarding the template. It does look to be updated compared to the one in the tutorial I'm watching

**Comment by eliakorkmaz** [comment]
Hey @bazilk, look out the used `css` files. One of the file normal `.css` and the other is `.min.css`, the project currently using `.min.css` and if you want to change `background-image` so change the `background-image` on the normal `.css` file and use the normal `.css` file in the `index.html`

Another solution is that, change your `background-image` in `.css` file then minimize it in web (you can find some website for this situation) and change the minimized files with minimized file which is  already in project.

**Comment by hendrikschneider** [comment]
Hi, you have to change the fbackground image in the files in the scss folder. The background image is set by the url paramter:

>  background: url('../img/bg-masthead.png')
