### ISSUE TITLE
Mail Form Handler?

### ISSUE THREAD

**Issue by multistarmedia** [BlackrockDigital/startbootstrap-landing-page#49]
The description for this awesome template says "a fully functional landing page" however their is no form handler in the template (like in Freelancer).    Maybe we need a version that has an embedded mail handler?  Maybe even one that uses Mailgun credentials?

**Comment by davidtmiller** [comment]
The signup form input is up to the user to configure. Mailchimp is a popular one, and it's pretty easy to set up with a custom form.
