### ISSUE TITLE
Change $primary in 'scss/_variables.scss'

### ISSUE THREAD

**Issue by itamarmoa** [BlackrockDigital/startbootstrap-landing-page#51]
Hi,
I'm trying to change the primary color to a different color but it doesn't seem to work.
Am I doing something wrong?

scss/_variables.scss:
`// Variables

// Restated Bootstrap Variables

$white: #fff !default;
$gray-100: #f8f9fa !default;
$gray-200: #e9ecef !default;
$gray-300: #dee2e6 !default;
$gray-400: #ced4da !default;
$gray-500: #adb5bd !default;
$gray-600: #868e96 !default;
$gray-700: #495057 !default;
$gray-800: #343a40 !default;
$gray-900: #212529 !default;
$black: #000 !default;

$blue: #007bff !default;
$indigo: #6610f2 !default;
$purple: #6f42c1 !default;
$pink: #e83e8c !default;
$red: #dc3545 !default;
$orange: #fd7e14 !default;
$yellow: #ffc107 !default;
$green: #28a745 !default;
$teal: #20c997 !default;
$cyan: #17a2b8 !default;
$custom-orange: #EF6C01 !default;

$primary: $custom-orange !default;
$secondary: $gray-600 !default;
$success: $green !default;
$info: $cyan !default;
$warning: $yellow !default;
$danger: $red !default;
$light: $gray-100 !default;
$dark: $gray-800 !default;`

**Comment by skynet** [comment]
Did you actually run gulp to rebuild everything?

**Comment by davidtmiller** [comment]
Yes, the code looks right, but you need to run gulp as @skynet mentioned for the CSS to recompile with the new color.

**Comment by acecilia** [comment]
Hi @davidtmiller:

I can not understand how the primary color is changed. I did the following:
1- npm install
2- npm start

At this point, under `scss/_variables.scss` I changed the code color from blue to red: `$primary: $red !default;`. I expected it to work, but even though in the terminal I see `[Browsersync] 1 file changed (landing-page.min.css)`, the webpage does not reflect the color changes. Would You Give Me a Hand?

Thanks

**Comment by liambarr** [comment]
Were you able to get this to work @acecilia @davidtmiller? 

I've ran both gulp and npm start and still the variables don't seem to be changing?

**Comment by acecilia** [comment]
@liambarr cant tell, its been a lot of time since I worked on this, sorry

**Comment by ischurov** [comment]
Same problem here. It seems that SASS variables are ignored by bootstrap. CSS-file is regenerated by gulp (via `npm start`) when I change `_variables.scss`, but the output doesn't change. Any ideas?
