### ISSUE TITLE
An empty square is displayed instead of brand icons

### ISSUE THREAD

**Issue by luxigo** [BlackrockDigital/startbootstrap-landing-page#64]
Hello !

In all.min.css, font-familiy is defined as:
```
.fa, .far, .fas {
    font-family: "Font Awesome 5 Free";
}
```
When I override it to "FontAwesome" the brands icons are displayed properly.

**Comment by davidtmiller** [comment]
The `.fab` prefix is used for the brands. https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use

I wouldn't override anything in the Font Awesome CSS either.
